[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Michele 'TnTo' Ciruzzi <tnto@hotmail.it>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = ""
keywords = [""]

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
sphinx = "^3.2.1"
pytest-cov = "^2.10.1"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-import-order = "^0.18.1"
coverage = {version = "^5.3", extras = ["toml"]}
mypy = "^0.782"
flake8-annotations = "^2.4.1"
flake8-docstrings = "^1.5.0"
darglint = "^1.5.5"
xdoctest = "^0.15.0"
sphinx-autodoc-typehints = "^1.11.0"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["example"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
